[pytest]
python_files = test_*
python_functions = test_*
python_classes = Test*
testpaths = .
addopts = --alluredir=allure-results
# This will automatically include --alluredir=allure-results to the pytest command.
addopts = --timeout=60000
# Change if the pages load too long

