[pytest]
python_files = test_*
python_functions = test_*
python_classes = Test*
testpaths = .
addopts = --alluredir=allure-results --timeout=60000
# --alluredir=allure-results will automatically include both options to the pytest command.
# --timeout=60000 change if the pages download more than 60 seconds

