name: CI and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30 
    # Prevents jobs from hanging forever,limits runtime to 30 minutes.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # ============================================================================
      # ALTERNATIVE PATH: Run tests with Docker Compose (uncomment to use)
      # Note: Docker and default run of the tests can't be used simultaneously
      # ============================================================================
      #  - name: Create allure-results directory with proper permissions
      #   run: mkdir -p allure-results && chmod 777 allure-results
      # - name: Build and start services with Docker Compose
      #   run: |
      #     docker compose up --build --detach
      #     # --detach to run services in the background
      #     # --build to rebuild the image if Dockerfile or code is changed
      #
      # - name: Run tests
      #   run: pytest
      #
      # - name: Stop services
      #   run: docker compose down
      #
      # ============================================================================

      # ============================================================================
      # ACTIVE PATH: Run tests directly (default)
      # ============================================================================
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Playwright browsers
        run: playwright install --with-deps

      - name: Run tests
        run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    # Makes the deploy job dependent on the test job. If tests fail, deployment is skipped.
    permissions:
      contents: write
      # Grant it permission to push to the gh-pages branch.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public

 
    
